<?php

namespace Proxies\__CG__\BackendBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Bonsai extends \BackendBundle\Entity\Bonsai implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'BackendBundle\\Entity\\Bonsai' . "\0" . 'idbonsai', '' . "\0" . 'BackendBundle\\Entity\\Bonsai' . "\0" . 'tipo', '' . "\0" . 'BackendBundle\\Entity\\Bonsai' . "\0" . 'riego', '' . "\0" . 'BackendBundle\\Entity\\Bonsai' . "\0" . 'abono', '' . "\0" . 'BackendBundle\\Entity\\Bonsai' . "\0" . 'transplante', '' . "\0" . 'BackendBundle\\Entity\\Bonsai' . "\0" . 'pulverizar', '' . "\0" . 'BackendBundle\\Entity\\Bonsai' . "\0" . 'createdat', '' . "\0" . 'BackendBundle\\Entity\\Bonsai' . "\0" . 'imgpredefinida'];
        }

        return ['__isInitialized__', '' . "\0" . 'BackendBundle\\Entity\\Bonsai' . "\0" . 'idbonsai', '' . "\0" . 'BackendBundle\\Entity\\Bonsai' . "\0" . 'tipo', '' . "\0" . 'BackendBundle\\Entity\\Bonsai' . "\0" . 'riego', '' . "\0" . 'BackendBundle\\Entity\\Bonsai' . "\0" . 'abono', '' . "\0" . 'BackendBundle\\Entity\\Bonsai' . "\0" . 'transplante', '' . "\0" . 'BackendBundle\\Entity\\Bonsai' . "\0" . 'pulverizar', '' . "\0" . 'BackendBundle\\Entity\\Bonsai' . "\0" . 'createdat', '' . "\0" . 'BackendBundle\\Entity\\Bonsai' . "\0" . 'imgpredefinida'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Bonsai $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdbonsai()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdbonsai();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdbonsai', []);

        return parent::getIdbonsai();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipo($tipo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipo', [$tipo]);

        return parent::setTipo($tipo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipo', []);

        return parent::getTipo();
    }

    /**
     * {@inheritDoc}
     */
    public function setRiego($riego)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRiego', [$riego]);

        return parent::setRiego($riego);
    }

    /**
     * {@inheritDoc}
     */
    public function getRiego()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRiego', []);

        return parent::getRiego();
    }

    /**
     * {@inheritDoc}
     */
    public function setAbono($abono)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAbono', [$abono]);

        return parent::setAbono($abono);
    }

    /**
     * {@inheritDoc}
     */
    public function getAbono()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAbono', []);

        return parent::getAbono();
    }

    /**
     * {@inheritDoc}
     */
    public function setTransplante($transplante)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTransplante', [$transplante]);

        return parent::setTransplante($transplante);
    }

    /**
     * {@inheritDoc}
     */
    public function getTransplante()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTransplante', []);

        return parent::getTransplante();
    }

    /**
     * {@inheritDoc}
     */
    public function setPulverizar($pulverizar)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPulverizar', [$pulverizar]);

        return parent::setPulverizar($pulverizar);
    }

    /**
     * {@inheritDoc}
     */
    public function getPulverizar()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPulverizar', []);

        return parent::getPulverizar();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedat($createdat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedat', [$createdat]);

        return parent::setCreatedat($createdat);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedat', []);

        return parent::getCreatedat();
    }

    /**
     * {@inheritDoc}
     */
    public function setImgpredefinida($imgpredefinida)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImgpredefinida', [$imgpredefinida]);

        return parent::setImgpredefinida($imgpredefinida);
    }

    /**
     * {@inheritDoc}
     */
    public function getImgpredefinida()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImgpredefinida', []);

        return parent::getImgpredefinida();
    }

}
