<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerL2luwaf\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerL2luwaf/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerL2luwaf.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerL2luwaf\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerL2luwaf\appDevDebugProjectContainer([
    'container.build_hash' => 'L2luwaf',
    'container.build_id' => 'd86216ed',
    'container.build_time' => 1573757478,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerL2luwaf');
