app_default:
    resource: '@AppBundle/Resources/Config/Routing/Default.yml'
    prefix: /

app_user:
    resource: '@AppBundle/Resources/Config/Routing/User.yml'
    prefix: /user

app_userBonsai:
    resource: '@AppBundle/Resources/Config/Routing/UserBonsai.yml'
    prefix: /userBonsai

app_logCuidados:
    resource: '@AppBundle/Resources/Config/Routing/LogCuidados.yml'
    prefix: /logCuidados